salerapp/Controllers/ListingController.cs
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using salerapp.Context;
using salerapp.Helpers;
using salerapp.Models;

namespace salerapp.Controllers
{
    /// <summary>
    /// Handles operations to do with garage sale listings.
    /// </summary>
    public class ListingController : Controller
    {
        public SalerContext db = new SalerContext();

        /// <summary>
        /// Toggles a listing from hidden to unhidden or unhidden to hidden.
        /// </summary>
        /// <param name="listingId">The ID of the listing to be hidden or unhidden.</param>
        /// <returns>Redirect to current page.</returns>
        public IActionResult ToggleHideListing(int listingId)
        {
            // Ensure that a user is currently logged in
            if (HttpContext.Session.GetString("_User") is not null)
            {
                // Retrieve the current listing
                Listing currentListing = db.Listings.First(l => l.ListingId == listingId);

                // Validate that the current user is the poster for this listing
                if (JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId == currentListing.PosterId)
                {
                    // Toggle hidden flag
                    currentListing.IsHidden = !currentListing.IsHidden;
                    db.SaveChanges();
                }

            }

            // Redirect to current page
            return Redirect(HttpContext.Request.Headers["Referer"].ToString());
        }

        /// <summary>
        /// Saves a listing in the Saler database for later viewing by a particular user.
        /// </summary>
        /// <param name="listingId">The ID of the listing to be saved by a user.</param>
        /// <returns>Rediret to current page.</returns>
        public IActionResult SaveListing(int listingId)
        {
            // Make sure a user is logged in
            if (HttpContext.Session.GetString("_User") is not null)
            {
                // Get user Id from session
                int userId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;

                // Ensure that the user does not have the listing currently saved before proceeding
                if (db.SavedListings.Where(s => s.UserId == userId && s.ListingId == listingId).Count() <= 0)
                {
                    // Create new saved listing relationship
                    SavedListing tempSaveListing = new SavedListing
                    {
                        ListingId = listingId,
                        UserId = userId,
                        SavedTime = DateTime.Now
                    };

                    // Add new saved listing to database
                    db.SavedListings.Add(tempSaveListing);
                    db.SaveChanges();
                }
            }

            // Redirect to current page
            return Redirect(HttpContext.Request.Headers["Referer"].ToString());
        }

        /// <summary>
        /// Removes the relationship between a user and a listing that they had previously saved.
        /// </summary>
        /// <param name="listingId">The ID of the listing to be unsaved by a user.</param>
        /// <returns>Redirect to current page.</returns>
        public IActionResult UnsaveListing(int listingId)
        {
            // Make sure a user is logged in
            if (HttpContext.Session.GetString("_User") is not null)
            {
                // Get user Id from session
                int userId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;

                // Make sure currently saved user has this listing saved
                if (db.SavedListings.Where(s => s.UserId == userId && s.ListingId == listingId).Count() >= 1)
                {
                    // Remove listing
                    db.SavedListings.Remove(db.SavedListings.Where(s => s.UserId == userId && s.ListingId == listingId).FirstOrDefault());
                    db.SaveChanges();
                }
            }

            // Redirect to current page
            return Redirect(HttpContext.Request.Headers["Referer"].ToString());
        }

        //[HttpPost]
        //public IActionResult SavePicture(ListingModel)
        //{
        //    if (file != null && file.Length > 0)
        //    {
        //        var fileName = Path.GetFileName(file.FileName);
        //        var blobContainer = new BlobContainerClient(Configuration.GetConnectionString("AzureStorageAccount"), "images");
        //        var blobClient = blobContainer.GetBlobClient(fileName);
        //        using (var stream = file.OpenReadStream())
        //        {
        //            await blobClient.UploadAsync(stream);
        //        }
        //    }

        //    return RedirectToPage("/AddListing");
        //}
    }
}

salerapp/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salerapp.Pages
{
    
}

salerapp/Pages/AccountSettings.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using salerapp.Context;
using salerapp.Helpers;
using salerapp.Models;

namespace salerapp.Pages
{
    /// <summary>
    /// PageModel for Add Listing page.
    /// </summary>
    public class AccountSettingsModel : PageModel
    {

        /// <summary>
        /// The context linking the application to the Saler database.
        /// </summary>
        public SalerContext db = new SalerContext();

        /// <summary>
        /// Warnings to display to the user.
        /// </summary>
        public List<String> warnings = new List<String>();

        public User LoadUser(int id)
        {
            return db.Users.Where(u => u.UserId == id).FirstOrDefault();
        }

        /// <summary>
        /// The user's password.
        /// </summary>
        [BindProperty]
        public string CurrentPassword { get; set; }

        [BindProperty]
        public string NewPassword { get; set; }


        public IActionResult OnPostUsername(User user)
        {

            int userId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;
            User currentUser = db.Users.Where(u => u.UserId == userId).FirstOrDefault();
            bool newUserName = db.Users.Where(u => String.Equals(u.UserName.ToLower(), user.UserName.ToLower())).Count() == 0;
            if (!newUserName)
            {
                // Validate that there are no existing users with the username
                warnings.Add("That username already exists. Please choose another username.");
                return Page();
            }
            else
            {
                currentUser.UserName = user.UserName;
                db.SaveChanges();
                // update username in session
                string userJson = HttpContext.Session.GetString("_User");
                User sessionUser = JsonConvert.DeserializeObject<User>(userJson);
                sessionUser.UserName = user.UserName;
                HttpContext.Session.SetString("_User", JsonConvert.SerializeObject(sessionUser));
                // return success message and reload the page
                TempData["Message"] = "Username updated successfully.";
                return Page();
            }
        }

        public IActionResult OnPostPassword()
        {
            string currentPassword = CurrentPassword;
            string newPassword = NewPassword;

            // Get user object
            int userId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;
            User currentUser = db.Users.Where(u => u.UserId == userId).FirstOrDefault();

            // Ensure user exists
            if (currentUser != null)
            {
                if (String.Equals(currentPassword, newPassword))
                {
                    warnings.Add("Your new password cannot match your current password.");
                }
                else if (String.Equals(EncryptionDecryptionHelper.Decrypt(currentUser.Password), currentPassword))
                {
                    // Encrypt password before saving
                    currentUser.Password = EncryptionDecryptionHelper.Encrypt(newPassword);
                    db.SaveChanges();
                    // return success message and reload the page
                    TempData["Message"] = "Password updated successfully.";
                }
                else
                {
                    // Password did not match database
                    warnings.Add("Your password was incorrect. Please try again.");
                }
            }
            else
            {
                warnings.Add("System error occurred. Please try again later.");
            }
            return Page();
        }
    }
}

salerapp/Pages/AddListing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using salerapp.Context;
using salerapp.Helpers;
using salerapp.Models;

namespace salerapp.Pages
{
    /// <summary>
    /// PageModel for Add Listing page.
    /// </summary>
    public class AddListingModel: PageModel
    {
        /// <summary>
        /// The listing to be added.
        /// </summary>
        public Listing Listing { get; set; }

        /// <summary>
        /// The context linking the application to the Saler database.
        /// </summary>
        public SalerContext db = new SalerContext();

        /// <summary>
        /// A list of state abbreviations for the state dropdown menu.
        /// </summary>
        public IEnumerable<SelectListItem> StateOptions = Listing.StateAbbreviations
            .Select(x => new SelectListItem() { Text = x.ToString() });

        /// <summary>
        /// Warnings to display to the user.
        /// </summary>
        public List<String> warnings = new List<String>();

        /// <summary>
        /// Submits a listing to the database upon form submission.
        /// </summary>
        /// <param name="listing">The listing to be added.</param>
        /// <returns>A redirect to the page of the new listing, or home page if an error occurred.</returns>
        [ValidateAntiForgeryToken]
        public IActionResult OnPost(Listing listing)
        {
            if (listing != null)
            {
                // Ensure logged in user is not null
                if (HttpContext.Session.GetString("_User") is null)
                {
                    warnings.Add("Please log in before submitting a listing.");
                    return null;
                } else
                {
                    // Get user ID from logged in user
                    listing.PosterId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;
                    listing.PostDate = DateTime.Now;

                    // Add listing
                    db.Listings.Add(listing);
                    db.SaveChanges();

                    //if (listing.Images != null) {
                        // do the image upload to the database
                    //}

                    // Redirect to listing page
                    return Redirect("~/listing?id=" + listing.ListingId);
                }

            } else
            {
                warnings.Add("An error occured in processing your listing.");
                return Redirect("~/");
            }
        }
    }
}

salerapp/Pages/DeleteAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using salerapp.Context;
using salerapp.Models;
using System.Reflection;

namespace salerapp.Pages
{
    public class DeleteAccountModel : PageModel
    {
        /// <summary>
        /// The context linking the application to the Saler database.
        /// </summary>
        public SalerContext db = new SalerContext();

        public IActionResult OnPost()
        {
            int userId = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId;
            User currentUser = db.Users.Where(u => u.UserId == userId).FirstOrDefault();

            if (currentUser == null)
            {
                // Redirect if no user logged in
                return Redirect("~/");
            }

            // Remove all listings associated with the user
            List<Listing> listingsToRemove = db.Listings.Where(l => l.PosterId == userId).ToList();
            db.Listings.RemoveRange(listingsToRemove);

            // Remove all of the user's saved listings
            List<SavedListing> savedListings = db.SavedListings.Where(s => s.UserId == userId).ToList();
            db.SavedListings.RemoveRange(savedListings);

            // Remove the user's account
            db.Users.Remove(currentUser);

            // Save changes to the database
            db.SaveChanges();

            // Clear the session and redirect to the home page
            HttpContext.Session.Clear();
            TempData["Message"] = "Account deleted successfully.";
            return Redirect("~/");
        }
    }
}

salerapp/Pages/DeleteListing.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using salerapp.Context;
using salerapp.Models;
using System.Reflection;

namespace salerapp.Pages
{
    public class DeleteListingModel : PageModel
    {
        /// <summary>
        /// The context linking the application to the Saler database.
        /// </summary>
        public SalerContext db = new SalerContext();
        /// <summary>
        /// Retrieves the details of the original listing.
        /// </summary>
        /// <param name="id">The listing ID of the original listing.</param>
        /// <returns>The desired listing and its details.</returns>
        public Listing LoadListing(int id)
        {
            return db.Listings.Where(l => l.ListingId == id).FirstOrDefault();
        }

        public IActionResult OnPost(Listing listing)
        {
            // Get the current listing based on ID
            Listing currentListing = db.Listings.Where(l => l.ListingId == listing.ListingId).FirstOrDefault();

            if (currentListing is null || HttpContext.Session.GetString("_User") is null)
            {
                // Redirect if listing not found or no user logged in
                return Redirect("~/");
            }
            else if (JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId != currentListing.PosterId)
            {
                // Redirect if logged in user does not match original listing poster
                return Redirect("~/");
            }
            else
            {

                // Remove listing information that could've changed
                db.Listings.Remove(currentListing);
                // Remove saved listings relationships
                var savedListings = db.SavedListings.Where(l => l.ListingId == currentListing.ListingId).ToList();
                foreach (SavedListing sl in savedListings)
                {
                    db.SavedListings.Remove(sl);
                }
                TempData["Message"] = "Listing Deleted Successfully";
                TempData.Keep();

                db.SaveChanges();
                return Redirect("~/MyListings");
            }
        }
    }
}

salerapp/Pages/Explore.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using salerapp.Context;
using salerapp.Helpers;
using salerapp.Models;

namespace salerapp.Pages
{
    /// <summary>
    /// PageModel for the Explore page.
    /// </summary>
    public class ExploreModel: PageModel
    {
        /// <summary>
        /// The context linking the application to the Saler database.
        /// </summary>
        public SalerContext db = new SalerContext();

        /// <summary>
        /// The list of listings to be viewed.
        /// </summary>
        public IEnumerable<Listing> listings;

        /// <summary>
        /// A dictionary linking listing ID to the poster ID.
        /// </summary>
        public Dictionary<int, String> userNames = new Dictionary<int, String>();

        /// <summary>
        /// Retrieves the listings to be displayed.
        /// </summary>
        public void LoadListings()
        {
            // Sort listings
            listings = db.Listings.OrderByDescending(l => l.PostDate);

            // Get usernames for display in explore page
            foreach (Listing listing in db.Listings) {
                String userName = db.Users.Where(u => u.UserId == listing.PosterId).SingleOrDefault().UserName;
                userNames.Add(listing.ListingId, (userName is null) ? "Unknown" : userName);
            }
        }
    }
}

salerapp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salerapp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

salerapp/Pages/Resources.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salerapp.Pages
{
    
}

salerapp/Pages/Team.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace salerapp.Pages
{
    
}

salerapp/Pages/AccountSettings.cshtml
@page
@model salerapp.Pages.AccountSettingsModel
@{
    ViewData["Title"] = "Account Settings";
    User user = new User();
    // Redirect if no user is currently logged in; else load listing information
    if (HttpContextAccessor.HttpContext.Session.GetString("_User") is null)
    {
        Response.Redirect("/");
    }
    else
    {
        user = Model.LoadUser(JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId);
    }

}

<!-- Warning messages -->
@foreach (var warning in Model.warnings)
{
    <div class="alert alert-danger" role="alert" style="margin-top: 5%; margin-left: 27.5%; margin-right: 27.5%;">
        @warning
    </div>
}
@try
{
    @if (JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")) is not null)
    {
        // Ensure current user matches the poster of the listing
        if (JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("_User")).UserId == user.UserId)
        {
            <div style="margin-left: 27.5%; margin-right: 27.5%; margin-top: 5%;">
                @if (TempData["Message"] != null)
                {
                    <div class="alert alert-success">@TempData["Message"]</div>
                }
            </div>
            <!-- Main form -->
            <main class="form w-100 m-auto text-center container">
                <h1 class="display-6 fw-bold lh-1 mb-4" style="text-align:left; margin-left: 27.5%">Account Settings</h1>
                <form id="changeUsername" style="margin-left: 37.5%; margin-right: 37.5%; margin-top: 5%;" method="post" asp-page-handler="Username">
                    <h3 style="margin-bottom:15px;">Change Username</h3>
                    <div class="form-floating" style="margin: 5px;">
                        @(Html.TextBoxFor(t => user.UserName, new { @type = "text", @class = "form-control", @id = "floatingInput", @required = "true" }))
                        <label for="username">New Username *</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" style="margin-top: 5px;" type="submit">Update Username</button>
                </form>
                <form id="changePassword" style="margin-left: 37.5%; margin-right: 37.5%; margin-top: 5%;" method="post" asp-page-handler="Password">
                    <h3 style="margin-bottom:15px;">Change Password</h3>
                    <div class="form-floating" style="margin: 5px;">
                        @(Html.PasswordFor(t => t.CurrentPassword, new { @class = "form-control", @id = "floatingInput", @required = "true", @value = "" }))
                        <label for="currentPassword">Current Password *</label>
                    </div>

                    <div class="form-floating" style="margin: 5px;">
                        @(Html.TextBoxFor(t => t.NewPassword, new { @type = "password", @class = "form-control", @id = "floatingInput", @required = "true", @value = "" }))
                        <label for="newPassword">New Password *</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" style="margin-top: 5px;" type="submit">Update Password</button>
                </form>
                <br />
                <div style="margin-left: 37.5%; margin-right: 37.5%; margin-top: 5%;">
                    <a role="button" class="w-100 btn btn-lg btn-danger" href="@Url.Content("/DeleteAccount")">Delete Account</a>
                </div>

                <script>
                    $(document).ready(function () {
                        $("form").submit(function (e) {
                            e.preventDefault();
                            var form = $(this);
                            var url = form.attr("action");
                            var formData = form.serialize();
                            var submitButtonName = $(document.activeElement).attr('name');

                            $.ajax({
                                type: "POST",
                                url: url,
                                data: formData,
                                success: function (result) {
                                    if (submitButtonName === "changeUsername") {
                                        // Update the username in the navbar
                                        $("#username-navbar").text(result);
                                    }
                                },
                                error: function () {
                                    // Show error message
                                    $("#error-alert").show();

                                    // Hide error message after 3 seconds
                                    setTimeout(function () {
                                        $("#error-alert").hide();
                                    }, 3000);
                                }
                            });
                        });
                    });
                </script>
            </main>
        }
        else
        {
            // Redirect to home page
            Response.Redirect("/");
        }
    }
}
catch (ArgumentNullException)
{
    // Redirect to home page
    Response.Redirect("/");
}

salerapp/Pages/Explore.cshtml
@page
@model ExploreModel
@{
    ViewData["Title"] = "Explore Listings";

    // Load recent listings
    Model.LoadListings();

    // Variable for user Id
    int userId = -1;

    // Check that user is logged in, then retrieve user ID if true
    if (HttpContextAccessor.HttpContext.Session.GetString("_User") is not null)
    {
        userId = JsonConvert.DeserializeObject<User>(HttpContextAccessor.HttpContext.Session.GetString("_User")).UserId;
    }
}

<main class="form w-100 m-auto text-center container">
    <div style="margin-left: 12.5%; margin-right: 12.5%; margin-top: 5%;">
        <h1 class="display-6 fw-bold lh-1 mb-4" style="text-align:left;">Explore Listings</h1>

        <div class="listings">
            <!-- Get 20 latest listings -->
            @foreach (Listing listing in Model.listings.Where(l => !l.IsHidden).Take(20))
            {
                string formattedAddress = ""; 
                @try {
                    formattedAddress = @listing.StreetAddress.Replace(' ', '+');
                } catch(Exception ex) {
                    // if it does not work, ie no address is given, it will default to the city
                }
                string website = "http://google.com/maps/dir/?api=1&destination=" + formattedAddress + "+" + @listing.City + "+" + @listing.State + "+" + (listing.ZIPCode <= 10000 ? "0" : "") + @listing.ZIPCode;

                <!-- Listing card -->
                <div class="card mb-3" style="text-align:left;">
                    <div class="row">
                        <div class="col-sm-6">
                            <h5 class="card-title mt-2" style="margin-left: 10px;">
                                @listing.StartDate.ToShortDateString() @listing.StartDate.ToShortTimeString() - @listing.EndDate.ToShortDateString() @listing.EndDate.ToShortTimeString()
                                @if (userId > 0)
                                {
                                    // Apply saved badge
                                    if (Model.db.SavedListings.Where(s => s.UserId == userId && s.ListingId == listing.ListingId).Count() > 0)
                                    {
                                        <span class="badge bg-success">Saved</span>
                                    }
                                }
                            </h5>
                        </div>
                        <div class="col-sm-5" style="text-align: right;">
                            <h6 class="card-subtitle mt-2">
                                Posted by @Model.userNames.GetValueOrDefault(listing.ListingId)
                            </h6>
                        </div>
                    </div>
                    <h6 class="card-subtitle mt-2" style="margin-left: 10px;">
                        @listing.StreetAddress, @listing.City, @listing.State @((listing.ZIPCode <= 10000 ? "0" : ""))@listing.ZIPCode
                    </h6>
                    <div class="card-body">
                        <strong>Description:</strong> 
                        @if (listing.Description.Length > 500)
                        {
                            // Shorten description if it exceeds 500 characters
                            @string.Format("{0}{1}", listing.Description.Substring(0, 496), "...")
                        }
                        else
                        {
                            @listing.Description
                        }
                    </div>
                    <!-- Button panel -->
                    <div class="card-body" style="text-align: right; padding-top: 0rem;">
                        <a role="button" class="btn btn-dark btn-sm" target="_blank" href="@website">Route</a>
                        @if(userId > 0) {
                            // Check if listing is saved
                            if (Model.db.SavedListings.Where(s => s.UserId == userId && s.ListingId == listing.ListingId).Count() > 0)
                            {
                                @Html.ActionLink("Unsave", "UnsaveListing", "Listing", new { listing.ListingId }, new {@class="btn btn-dark btn-sm", @role="button"})
                            } else
                            {
                                @Html.ActionLink("Save", "SaveListing", "Listing", new { listing.ListingId }, new {@class="btn btn-dark btn-sm", @role="button"})
                            }
                        }
                        <a role="button" class="btn btn-dark btn-sm" href="@Url.Content("~/listing?id=" + listing.ListingId)">View</a>
                    </div>
                </div>
            }
        </div>
    </div>
</main>

salerapp/Pages/MyListings.cshtml
@page
@model MyListingsModel
@{
    ViewData["Title"] = "My Listings";

    // Ensure user is logged in, then either load listings or redirect page
    if (HttpContextAccessor.HttpContext.Session.GetString("_User") is not null)
    {
        Model.LoadListings();
    } else
    {
        Response.Redirect("/");
    }

}

<!-- Main form -->
<main class="form w-100 m-auto text-center container">
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-success">@TempData["Message"]</div>
    }
    <div style="margin-left: 12.5%; margin-right: 12.5%; margin-top: 5%;">
        <h1 class="display-6 fw-bold lh-1 mb-4" style="text-align:left;">My Listings</h1>
        <!-- Listings -->
        <div class="listings">
            @if (Model.listings is not null)
            {
                foreach (Listing listing in Model.listings)
                {
                    <div class="card mb-3" style="text-align:left;">
                        <h5 class="card-title mt-2" style="margin-left: 10px;">
                            @listing.StartDate.ToShortDateString() @listing.StartDate.ToShortTimeString() - @listing.EndDate.ToShortDateString() @listing.EndDate.ToShortTimeString() 
                            @if(listing.IsHidden) {
                                <span class="badge bg-dark">Hidden</span>
                            }
                        </h5>
                        <h6 class="card-subtitle mt-2" style="margin-left: 10px;">
                            @listing.StreetAddress, @listing.City, @listing.State @((listing.ZIPCode <= 10000 ? "0" : ""))@listing.ZIPCode
                        </h6>
                        <div class="card-body">
                            <strong>Description:</strong>
                            @if (listing.Description.Length > 500)
                            {
                                @string.Format("{0}{1}", listing.Description.Substring(0, 496), "...")
                            }
                            else
                            {
                                @listing.Description
                            }
                        </div>
                        <!-- Action button panel -->
                        <div class="card-body" style="text-align: right; padding-top: 0rem;">
                            @if (!listing.IsHidden) 
                            {
                                @Html.ActionLink("Hide", "ToggleHideListing", "Listing", new { listing.ListingId }, new {@class="btn btn-dark btn-sm", @role="button"})
                            } else
                            {
                                @Html.ActionLink("Unhide", "ToggleHideListing", "Listing", new { listing.ListingId }, new {@class="btn btn-dark btn-sm", @role="button"})
                            }
                            <a role="button" class="btn btn-dark btn-sm" href="@Url.Content("~/editlisting?id=" + listing.ListingId)">Edit</a>
                            <a role="button" class="btn btn-dark btn-sm" href="@Url.Content("~/deletelisting?id=" + listing.ListingId)">Delete</a>
                            <a role="button" class="btn btn-dark btn-sm" href="@Url.Content("~/listing?id=" + listing.ListingId)">View</a>
                        </div>
                    </div>
                }
                @if (Model.listings.Count() <= 0)
                {
                    // Message for users without listings
                    <h5 style="font-style: italic; margin-top: 50px; margin-bottom: 20px;">
                        No listings found...<a href="@Url.Content("~/AddListing")">add one today</a>.
                    </h5>
                }
            }
        </div>
    </div>
</main>